from __future__ import annotations

from datetime import UTC, datetime, timedelta


class NbaDataService:
    def __init__(self) -> None:
        self.now = datetime.now(UTC)

    def market_seeds(self) -> list[dict]:
        today = self.now
        return [
            {
                "slug": "lakers-warriors-who-wins",
                "title": "Lakers vs Warriors - Who Wins?",
                "description": "Predict the winner based on form, injuries, and matchup efficiency.",
                "category": "Game Outcome",
                "market_type": "game_outcome",
                "oracle_source": "NBA Stats API + official box score confirmation",
                "expiry_at": today + timedelta(hours=7),
                "yes_probability": 0.58,
                "ai_confidence": 0.73,
                "volume": 184500,
                "liquidity": 92500,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Los Angeles Lakers vs Golden State Warriors",
                    "primary_subject": "Los Angeles Lakers",
                    "yes_label": "Lakers",
                    "no_label": "Warriors",
                    "probability_points": [0.51, 0.53, 0.55, 0.57, 0.58],
                    "team_form": {
                        "home_team": "Los Angeles Lakers",
                        "away_team": "Golden State Warriors",
                        "home_record_last_5": "4-1",
                        "away_record_last_5": "2-3",
                        "home_off_rating": 118.7,
                        "away_off_rating": 114.1,
                        "home_def_rating": 111.2,
                        "away_def_rating": 115.9,
                    },
                    "player_context": {
                        "headline": "LeBron James",
                        "trend": "Lakers created a paint advantage in 4 of the last 5 games.",
                    },
                },
            },
            {
                "slug": "celtics-bucks-who-wins",
                "title": "Celtics vs Bucks - Who Wins?",
                "description": "Game outcome market with pace, rebounding, and shot-quality context.",
                "category": "Game Outcome",
                "market_type": "game_outcome",
                "oracle_source": "NBA Stats API + official box score confirmation",
                "expiry_at": today + timedelta(hours=10),
                "yes_probability": 0.61,
                "ai_confidence": 0.76,
                "volume": 203200,
                "liquidity": 108300,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Boston Celtics vs Milwaukee Bucks",
                    "primary_subject": "Boston Celtics",
                    "yes_label": "Celtics",
                    "no_label": "Bucks",
                    "probability_points": [0.55, 0.56, 0.58, 0.6, 0.61],
                    "team_form": {
                        "home_team": "Boston Celtics",
                        "away_team": "Milwaukee Bucks",
                        "home_record_last_5": "5-0",
                        "away_record_last_5": "3-2",
                        "home_off_rating": 121.4,
                        "away_off_rating": 117.3,
                        "home_def_rating": 109.8,
                        "away_def_rating": 113.1,
                    },
                    "player_context": {
                        "headline": "Jayson Tatum",
                        "trend": "Boston is winning the turnover battle and generating more corner threes.",
                    },
                },
            },
            {
                "slug": "knicks-heat-who-wins",
                "title": "Knicks vs Heat - Who Wins?",
                "description": "Live game market with in-game score pressure and foul trouble context.",
                "category": "Game Outcome",
                "market_type": "game_outcome",
                "oracle_source": "NBA live game feed + official final score",
                "expiry_at": today + timedelta(hours=2),
                "yes_probability": 0.54,
                "ai_confidence": 0.68,
                "volume": 146800,
                "liquidity": 80400,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "New York Knicks vs Miami Heat",
                    "primary_subject": "New York Knicks",
                    "yes_label": "Knicks",
                    "no_label": "Heat",
                    "probability_points": [0.48, 0.5, 0.49, 0.52, 0.54],
                    "team_form": {
                        "home_team": "New York Knicks",
                        "away_team": "Miami Heat",
                        "home_record_last_5": "3-2",
                        "away_record_last_5": "3-2",
                        "home_off_rating": 115.2,
                        "away_off_rating": 112.6,
                        "home_def_rating": 110.9,
                        "away_def_rating": 111.7,
                    },
                    "player_context": {
                        "headline": "Jalen Brunson",
                        "trend": "Knicks second-unit shot creation has improved since halftime.",
                    },
                },
            },
            {
                "slug": "lebron-james-30-plus-points",
                "title": "Will LeBron James score 30+ points?",
                "description": "Player prop powered by usage, matchup rim pressure, and minutes profile.",
                "category": "Player Performance",
                "market_type": "player_performance",
                "oracle_source": "NBA Stats API player tracking + official box score",
                "expiry_at": today + timedelta(hours=7),
                "yes_probability": 0.47,
                "ai_confidence": 0.69,
                "volume": 112000,
                "liquidity": 61700,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Los Angeles Lakers vs Golden State Warriors",
                    "primary_subject": "LeBron James",
                    "yes_label": "30+ Points",
                    "no_label": "Under 30",
                    "probability_points": [0.42, 0.44, 0.45, 0.46, 0.47],
                    "player_context": {
                        "headline": "LeBron James",
                        "trend": "Usage is up with more half-court reps and weak-side actions.",
                        "season_average": 27.4,
                    },
                    "team_form": {},
                },
            },
            {
                "slug": "stephen-curry-8-plus-assists",
                "title": "Will Stephen Curry record 8+ assists?",
                "description": "Player prop using recent touch time, lineup combinations, and trap rate.",
                "category": "Player Performance",
                "market_type": "player_performance",
                "oracle_source": "NBA Stats API passing dashboard + official box score",
                "expiry_at": today + timedelta(hours=7),
                "yes_probability": 0.39,
                "ai_confidence": 0.65,
                "volume": 87500,
                "liquidity": 53200,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Los Angeles Lakers vs Golden State Warriors",
                    "primary_subject": "Stephen Curry",
                    "yes_label": "8+ Assists",
                    "no_label": "Under 8",
                    "probability_points": [0.34, 0.35, 0.36, 0.38, 0.39],
                    "player_context": {
                        "headline": "Stephen Curry",
                        "trend": "Potential minute cap trims assist ceiling even if trap volume rises.",
                        "season_average": 6.2,
                    },
                    "team_form": {},
                },
            },
            {
                "slug": "nikola-jokic-12-plus-rebounds",
                "title": "Will Nikola Jokic grab 12+ rebounds?",
                "description": "Player prop driven by opponent shot profile and contested board share.",
                "category": "Player Performance",
                "market_type": "player_performance",
                "oracle_source": "NBA rebounding tracking + official box score",
                "expiry_at": today + timedelta(days=1, hours=1),
                "yes_probability": 0.63,
                "ai_confidence": 0.79,
                "volume": 97300,
                "liquidity": 58800,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Denver Nuggets vs Minnesota Timberwolves",
                    "primary_subject": "Nikola Jokic",
                    "yes_label": "12+ Rebounds",
                    "no_label": "Under 12",
                    "probability_points": [0.57, 0.59, 0.6, 0.62, 0.63],
                    "player_context": {
                        "headline": "Nikola Jokic",
                        "trend": "Frontcourt rebounding advantage remains intact against current lineups.",
                        "season_average": 12.4,
                    },
                    "team_form": {},
                },
            },
            {
                "slug": "nuggets-reach-finals",
                "title": "Will the Nuggets reach the Finals?",
                "description": "Season market using playoff path, rotation health, and efficiency trend.",
                "category": "Season Market",
                "market_type": "season_event",
                "oracle_source": "NBA standings + postseason resolution rules",
                "expiry_at": today + timedelta(days=52),
                "yes_probability": 0.44,
                "ai_confidence": 0.71,
                "volume": 261400,
                "liquidity": 143900,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "Denver Nuggets season outlook",
                    "primary_subject": "Denver Nuggets",
                    "yes_label": "Reach Finals",
                    "no_label": "Miss Finals",
                    "probability_points": [0.38, 0.39, 0.41, 0.43, 0.44],
                    "player_context": {
                        "headline": "Nikola Jokic",
                        "trend": "Half-court efficiency remains elite, but bracket path is demanding.",
                    },
                    "team_form": {
                        "home_team": "Denver Nuggets",
                        "conference_seed_projection": 2,
                    },
                },
            },
            {
                "slug": "shai-gilgeous-alexander-wins-mvp",
                "title": "Will Shai Gilgeous-Alexander win MVP?",
                "description": "Season market balancing award narrative, team record, and efficiency profile.",
                "category": "Season Market",
                "market_type": "season_event",
                "oracle_source": "NBA awards resolution + official announcement",
                "expiry_at": today + timedelta(days=38),
                "yes_probability": 0.36,
                "ai_confidence": 0.67,
                "volume": 217800,
                "liquidity": 124600,
                "metadata_json": {
                    "sport": "NBA",
                    "league": "NBA",
                    "matchup": "NBA MVP race",
                    "primary_subject": "Shai Gilgeous-Alexander",
                    "yes_label": "Wins MVP",
                    "no_label": "Does Not Win",
                    "probability_points": [0.29, 0.31, 0.33, 0.35, 0.36],
                    "player_context": {
                        "headline": "Shai Gilgeous-Alexander",
                        "trend": "Efficiency and team success keep him in the top tier of the race.",
                    },
                    "team_form": {},
                },
            },
        ]

    def live_games(self) -> list[dict]:
        base = self.now
        return [
            {
                "game_id": "nyk-mia-live",
                "matchup": "Knicks vs Heat",
                "status": "Q3 04:12",
                "tipoff_time": base - timedelta(hours=1, minutes=10),
                "home_team": "New York Knicks",
                "away_team": "Miami Heat",
                "home_score": 82,
                "away_score": 78,
                "win_probability_home": 0.58,
                "pace": 97.8,
                "headline": "Knicks bench unit swinging shot quality in transition.",
            },
            {
                "game_id": "lal-gsw-upcoming",
                "matchup": "Lakers vs Warriors",
                "status": "Pre-game",
                "tipoff_time": base + timedelta(hours=6, minutes=30),
                "home_team": "Los Angeles Lakers",
                "away_team": "Golden State Warriors",
                "home_score": 0,
                "away_score": 0,
                "win_probability_home": 0.58,
                "pace": 100.4,
                "headline": "Warriors injury watch is the largest late-moving variable.",
            },
            {
                "game_id": "bos-mil-upcoming",
                "matchup": "Celtics vs Bucks",
                "status": "Pre-game",
                "tipoff_time": base + timedelta(hours=9, minutes=15),
                "home_team": "Boston Celtics",
                "away_team": "Milwaukee Bucks",
                "home_score": 0,
                "away_score": 0,
                "win_probability_home": 0.61,
                "pace": 99.1,
                "headline": "Boston owns the matchup edge in spacing and weak-side defense.",
            },
        ]
